#!/usr/bin/env python

import os
import rospy
from geometry_msgs.msg import PoseStamped, Quaternion, TransformStamped, Vector3
import tf.transformations
import tf2_ros
from hippocampus_common.node import Node


class TfPublisherNode(Node):
    def __init__(self):
        super(TfPublisherNode, self).__init__("tf_publisher_node")

        self.camera_broadcaster = tf2_ros.StaticTransformBroadcaster()
        self.base_tf_broadcaster = tf2_ros.TransformBroadcaster()

        self.camera_link_transform = None
        self.camera_frame_transform = None

        self.camera_link_id = None
        self.camera_frame_id = None
        self.base_link_id = None

        self.broadcast_camera_tf()

        rospy.Subscriber("mavros/local_position/pose",
                         PoseStamped,
                         self.pose_callback,
                         queue_size=1)

    def pose_callback(self, pose):
        self.broadcast_baselink_tf(pose)

    def broadcast_camera_tf(self):
        link = self.get_camera_link_transform()
        frame = self.get_camera_frame_transform()
        self.camera_broadcaster.sendTransform([link, frame])

    def broadcast_baselink_tf(self, pose):
        transform = TransformStamped()
        transform.transform.translation = pose.pose.position
        transform.transform.rotation = pose.pose.orientation
        transform.header = pose.header
        transform.child_frame_id = self.get_base_link_id()

        self.base_tf_broadcaster.sendTransform(transform)

    def get_camera_link_transform(self):
        if not self.camera_link_transform:
            self.camera_link_transform = self._get_camera_link_transform()
        return self.camera_link_transform

    def _get_camera_link_transform(self):
        # read the pose from the parameter server
        pos_x = self._get_param("~camera/x", 0.0)
        pos_y = self._get_param("~camera/y", 0.0)
        pos_z = self._get_param("~camera/z", 0.0)
        roll = self._get_param("~camera/roll", 0.0)
        pitch = self._get_param("~camera/pitch", 0.0)
        yaw = self._get_param("~camera/yaw", 0.0)

        # create a transform message that will be returned by this function
        transform = TransformStamped()
        transform.header.stamp = rospy.Time.now()
        transform.header.frame_id = self.get_base_link_id()
        rospy.logerr(transform.header.frame_id)
        transform.child_frame_id = self.get_camera_link_id()

        transform.transform.translation = Vector3(x=pos_x, y=pos_y, z=pos_z)

        quat = tf.transformations.quaternion_from_euler(roll, pitch, yaw)

        transform.transform.rotation = Quaternion(x=quat[0],
                                                  y=quat[1],
                                                  z=quat[2],
                                                  w=quat[3])

        return transform

    def _get_camera_frame_transform(self):
        transform = TransformStamped()
        transform.header.stamp = rospy.Time.now()
        transform.header.frame_id = self.get_camera_link_id()
        transform.child_frame_id = self.get_camera_frame_id()

        quat = tf.transformations.quaternion_from_euler(-1.57, 0, -1.57)

        transform.transform.rotation = Quaternion(x=quat[0],
                                                  y=quat[1],
                                                  z=quat[2],
                                                  w=quat[3])
        return transform

    def get_camera_frame_transform(self):
        if not self.camera_frame_transform:
            self.camera_frame_transform = self._get_camera_frame_transform()
        return self.camera_frame_transform

    def _get_camera_frame_id(self):
        default = os.path.join(rospy.get_namespace(), "camera_frame")
        return self._get_param("~camera_frame", default)

    def get_camera_frame_id(self):
        if not self.camera_frame_id:
            self.camera_frame_id = self._get_camera_frame_id()
        return self.camera_frame_id

    def _get_camera_link_id(self):
        default = os.path.join(rospy.get_namespace(), "camera_link")
        return self._get_param("~camera_link", default)

    def get_camera_link_id(self):
        if not self.camera_link_id:
            self.camera_link_id = self._get_camera_link_id()
        return self.camera_link_id

    def _get_base_link_id(self):
        default = os.path.join(rospy.get_namespace(), "base_link")
        return self._get_param("~base_link", default)

    def get_base_link_id(self):
        if not self.base_link_id:
            self.base_link_id = self._get_base_link_id()
        return self.base_link_id


if __name__ == "__main__":
    node = TfPublisherNode()
    node.run()
