#!/usr/bin/env python
# DO NOT USE AT THE MOMENT. STILL WORK IN PROGRESS.
import sys
import os
import yaml
import numpy as np
import rospy
import rospkg
import tf.transformations
import tf2_ros
import tf2_geometry_msgs
from geometry_msgs.msg import PoseStamped
from hippocampus_common.node import Node
from apriltag_ros.msg import AprilTagDetectionArray
from mu_auv_localization.ekf import ExtendedKalmanFilter
import threading


class VisionEstimatorNode(Node):
    def __init__(self):
        super(VisionEstimatorNode, self).__init__("vision_estimator_node")

        self.lock = threading.Lock()
        self.t_last_prediction = rospy.get_time()
        self.tf_buffer = tf2_ros.Buffer()
        self.tf_listener = tf2_ros.TransformListener(self.tf_buffer)
        self.tf_buffer.lookup_transform(target_frame="map_ned",
                                        source_frame="map",
                                        time=rospy.Time(0),
                                        timeout=rospy.Duration(10))
        self.ekf = ExtendedKalmanFilter([0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0])

        self.vision_pose_pub = rospy.Publisher("mavros/vision_pose/pose",
                                               PoseStamped)

        rospy.Subscriber("tag_detections",
                         AprilTagDetectionArray,
                         self.apriltag_callback,
                         queue_size=1)

    def apriltag_callback(self, tag_array):
        detection_count = len(tag_array.detections)

        if detection_count:
            transform = self.tf_buffer.lookup_transform(
                target_frame="gazebo_bundle",
                source_frame="uuv00/base_link",
                time=rospy.Time(0),
                timeout=rospy.Duration(1))
            translation = transform.transform.translation
            quat = transform.transform.rotation
            measurement = np.array([
                translation.x, translation.y, translation.z, quat.x, quat.y,
                quat.z, quat.w
            ]).reshape(-1, 1)

            with self.lock:
                now = rospy.get_time()
                self.ekf.predict(now - self.t_last_prediction,
                                 np.array([0, 0, 0]))
                self.t_last_prediction = now
                self.ekf.update(0.0, measurement)

            self._publish_pose_estimation()

    def _publish_pose_estimation(self):
        estimation = self.ekf._x
        position = estimation[:3]
        orientation = estimation[3:7]
        pose = PoseStamped()
        pose.pose.position.x = position[0]
        pose.pose.position.y = position[1]
        pose.pose.position.z = position[2]
        pose.pose.orientation.x = orientation[0]
        pose.pose.orientation.y = orientation[1]
        pose.pose.orientation.z = orientation[2]
        pose.pose.orientation.w = orientation[3]
        pose.header.stamp = rospy.Time.now()
        pose.header.frame_id = "map"
        self.vision_pose_pub.publish(pose)


def main():
    node = VisionEstimatorNode()
    node.run()


if __name__ == "__main__":
    main()
