tag_bundles:
  - layout:
      - {
          id: 0,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 1.56,
          y: 0.06,
          z: -1.3,
        }
      - {
          id: 1,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 1.31,
          y: 0.06,
          z: -1.3,
        }
      - {
          id: 2,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 1.06,
          y: 0.06,
          z: -1.3,
        }
      - {
          id: 3,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.81,
          y: 0.06,
          z: -1.3,
        }
      - {
          id: 4,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.56,
          y: 0.06,
          z: -1.3,
        }
      - {
          id: 5,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.31,
          y: 0.06,
          z: -1.3,
        }
      - {
          id: 6,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.06,
          y: 0.06,
          z: -1.3,
        }
      - {
          id: 7,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 1.56,
          y: 0.45375,
          z: -1.3,
        }
      - {
          id: 8,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 1.31,
          y: 0.45375,
          z: -1.3,
        }
      - {
          id: 9,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 1.06,
          y: 0.45375,
          z: -1.3,
        }
      - {
          id: 10,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.81,
          y: 0.45375,
          z: -1.3,
        }
      - {
          id: 11,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.56,
          y: 0.45375,
          z: -1.3,
        }
      - {
          id: 12,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.31,
          y: 0.45375,
          z: -1.3,
        }
      - {
          id: 13,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.06,
          y: 0.45375,
          z: -1.3,
        }
      - {
          id: 14,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 1.56,
          y: 0.8474999999999999,
          z: -1.3,
        }
      - {
          id: 15,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 1.31,
          y: 0.8474999999999999,
          z: -1.3,
        }
      - {
          id: 16,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 1.06,
          y: 0.8474999999999999,
          z: -1.3,
        }
      - {
          id: 17,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.81,
          y: 0.8474999999999999,
          z: -1.3,
        }
      - {
          id: 18,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.56,
          y: 0.8474999999999999,
          z: -1.3,
        }
      - {
          id: 19,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.31,
          y: 0.8474999999999999,
          z: -1.3,
        }
      - {
          id: 20,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.06,
          y: 0.8474999999999999,
          z: -1.3,
        }
      - {
          id: 21,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 1.56,
          y: 1.24125,
          z: -1.3,
        }
      - {
          id: 22,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 1.31,
          y: 1.24125,
          z: -1.3,
        }
      - {
          id: 23,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 1.06,
          y: 1.24125,
          z: -1.3,
        }
      - {
          id: 24,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.81,
          y: 1.24125,
          z: -1.3,
        }
      - {
          id: 25,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.56,
          y: 1.24125,
          z: -1.3,
        }
      - {
          id: 26,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.31,
          y: 1.24125,
          z: -1.3,
        }
      - {
          id: 27,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.06,
          y: 1.24125,
          z: -1.3,
        }
      - {
          id: 28,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 1.56,
          y: 1.635,
          z: -1.3,
        }
      - {
          id: 29,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 1.31,
          y: 1.635,
          z: -1.3,
        }
      - {
          id: 30,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 1.06,
          y: 1.635,
          z: -1.3,
        }
      - {
          id: 31,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.81,
          y: 1.635,
          z: -1.3,
        }
      - {
          id: 32,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.56,
          y: 1.635,
          z: -1.3,
        }
      - {
          id: 33,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.31,
          y: 1.635,
          z: -1.3,
        }
      - {
          id: 34,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.06,
          y: 1.635,
          z: -1.3,
        }
      - {
          id: 35,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 1.56,
          y: 2.02875,
          z: -1.3,
        }
      - {
          id: 36,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 1.31,
          y: 2.02875,
          z: -1.3,
        }
      - {
          id: 37,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 1.06,
          y: 2.02875,
          z: -1.3,
        }
      - {
          id: 38,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.81,
          y: 2.02875,
          z: -1.3,
        }
      - {
          id: 39,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.56,
          y: 2.02875,
          z: -1.3,
        }
      - {
          id: 40,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.31,
          y: 2.02875,
          z: -1.3,
        }
      - {
          id: 41,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.06,
          y: 2.02875,
          z: -1.3,
        }
      - {
          id: 42,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 1.56,
          y: 2.4225,
          z: -1.3,
        }
      - {
          id: 43,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 1.31,
          y: 2.4225,
          z: -1.3,
        }
      - {
          id: 44,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 1.06,
          y: 2.4225,
          z: -1.3,
        }
      - {
          id: 45,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.81,
          y: 2.4225,
          z: -1.3,
        }
      - {
          id: 46,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.56,
          y: 2.4225,
          z: -1.3,
        }
      - {
          id: 47,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.31,
          y: 2.4225,
          z: -1.3,
        }
      - {
          id: 48,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.06,
          y: 2.4225,
          z: -1.3,
        }
      - {
          id: 49,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 1.56,
          y: 2.81625,
          z: -1.3,
        }
      - {
          id: 50,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 1.31,
          y: 2.81625,
          z: -1.3,
        }
      - {
          id: 51,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 1.06,
          y: 2.81625,
          z: -1.3,
        }
      - {
          id: 52,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.81,
          y: 2.81625,
          z: -1.3,
        }
      - {
          id: 53,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.56,
          y: 2.81625,
          z: -1.3,
        }
      - {
          id: 54,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.31,
          y: 2.81625,
          z: -1.3,
        }
      - {
          id: 55,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.06,
          y: 2.81625,
          z: -1.3,
        }
      - {
          id: 56,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 1.56,
          y: 3.21,
          z: -1.3,
        }
      - {
          id: 57,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 1.31,
          y: 3.21,
          z: -1.3,
        }
      - {
          id: 58,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 1.06,
          y: 3.21,
          z: -1.3,
        }
      - {
          id: 59,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.81,
          y: 3.21,
          z: -1.3,
        }
      - {
          id: 60,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.56,
          y: 3.21,
          z: -1.3,
        }
      - {
          id: 61,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.31,
          y: 3.21,
          z: -1.3,
        }
      - {
          id: 62,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.06,
          y: 3.21,
          z: -1.3,
        }
    name: gazebo_bundle
